name: iSCALE_env
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - adwaita-icon-theme=49.0=unix_0
  - aom=3.9.1=hac33072_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - blas=1.0=mkl
  - blosc=1.21.6=he440d0b_1
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brunsli=0.1=he3183e4_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.19.1=h4cfbee9_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - cffi=2.0.0=py310h34a4b09_0
  - cfitsio=4.6.3=ha0b56bc_0
  - charls=2.4.2=h59595ed_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - epoxy=1.5.10=hb03c661_2
  - expat=2.7.1=h6a678d5_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gdk-pixbuf=2.44.3=h2b0a6b4_0
  - ghostscript=10.06.0=hecca717_0
  - giflib=5.2.2=hd590300_0
  - glib-tools=2.86.0=hf516916_0
  - graphite2=1.3.14=hecca717_2
  - graphviz=13.1.2=h87b6fe6_0
  - gtk3=3.24.43=h021d004_4
  - gts=0.7.6=h977cf35_4
  - harfbuzz=12.1.0=h15599e2_0
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hicolor-icon-theme=0.17=ha770c72_2
  - icu=75.1=he02047a_0
  - imagecodecs=2025.3.30=py310h4eb8eaf_2
  - imagemagick=7.1.2_6=gpl_hacdf01b_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jbig=2.1=h7f98852_2003
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.1=gpl_h98cc613_100
  - libavif16=1.3.0=h6395336_2
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.24=h86f0d12_0
  - libdicom=1.2.0=hb03c661_1
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libegl-devel=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexif=0.6.21=h7f98852_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgd=2.3.3=h6f5c62b_11
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libgl-devel=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libglx-devel=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libheif=1.19.7=gpl_hc18d805_100
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libjxl=0.11.1=h6cb5226_4
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmatio=1.5.28=h3671a80_3
  - libnghttp2=1.67.0=had1ee68_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - librsvg=2.58.4=h49af25d_2
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.7.1=h8261f1e_0
  - libuuid=1.41.5=h5eee18b_0
  - libvips=8.17.2=h9217f9d_1
  - libwebp=1.6.0=h9635ea4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h04c0eec_1
  - libzlib=1.3.1=hb25bd0a_0
  - libzopfli=1.0.3=h9c3ff4c_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - ncurses=6.5=h7934f7d_0
  - nspr=4.37=h29cc59b_0
  - nss=3.117=h445c969_0
  - numexpr=2.11.0=py310hf4471f9_0
  - numpy=2.0.1=py310h5f9d8c6_1
  - numpy-base=2.0.1=py310hb5e798b_1
  - openjpeg=2.5.4=h55fea9a_0
  - openslide=4.0.0=hacc1dc6_4
  - openssl=3.5.4=h26f9b46_0
  - pandas=2.3.3=py310h505adc9_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h54a6638_1
  - pkg-config=0.29.2=h4bc722e_1009
  - poppler=25.07.0=h13eef12_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=py310h06a4308_0
  - pyvips=3.0.0=py310h332dc74_3
  - rav1e=0.7.1=h8fae777_3
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=py310h06a4308_0
  - snappy=1.2.2=h03e3b7b_0
  - sqlite=3.50.2=hb25bd0a_1
  - svt-av1=3.1.2=hecca717_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wayland=1.24.0=h3e06ad9_0
  - wheel=0.45.1=py310h06a4308_0
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zfp=1.0.1=h909a3a2_3
  - zlib=1.3.1=hb25bd0a_0
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - einops==0.8.1
      - filelock==3.20.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - hdbscan==0.8.40
      - idna==3.11
      - imageio==2.37.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.4.2
      - numba==0.62.1
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==11.3.0
      - propcache==0.4.1
      - pycparser==2.23
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pytorch-lightning==2.5.5
      - pyyaml==6.0.3
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - torch==2.8.0
      - torchmetrics==1.8.2
      - torchvision==0.23.0
      - tqdm==4.67.1
      - triton==3.4.0
      - typing-extensions==4.15.0
      - umap-learn==0.5.9.post2
      - yarl==1.22.0
prefix: /home/aschro32/miniconda3/envs/iSCALE_env
